version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries: '*'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    registries: '*'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
