# Javascript Node CircleCI 2.0 configuration file
version: 2

docker-install: &docker-setup
  docker:
    - image: circleci/node:latest
  working_directory: ~/repo

yarn-config: &yarn-config
  run: yarn config set ${PRIVATE_NPM_REPO_URL}

restore-dep-cache: &restore-dep-cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

restore-ssh-cache: &restore-ssh-cache
  restore_cache:
    keys:
      - v1-ssh-{{ .Branch }}

git-config: &git-config
  run: git config --global user.email ${GIT_PRIVATE_EMAIL} && git config --global user.name ${GIT_PRIVATE_NAME}

git-commit-tags: &git-commit-tags
  run: git push --follow-tags

jobs:
  install:
    <<: *docker-setup
    steps:
      - checkout
      - *restore-dep-cache
      - *yarn-config
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - ~/.ssh/known_hosts
          key: v1-ssh-{{ .Branch }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint:
    <<: *docker-setup
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore-dep-cache
      - run: yarn lint

  test:
    <<: *docker-setup
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore-dep-cache
      - run: yarn test
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

  build:
    <<: *docker-setup
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore-dep-cache
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: dist

  patch:
    <<: *docker-setup
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore-ssh-cache
      - *git-config
      - run: npm version patch
      - *git-commit-tags

  minor:
    <<: *docker-setup
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore-ssh-cache
      - *git-config
      - run: npm version minor
      - *git-commit-tags

  major:
    <<: *docker-setup
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore-ssh-cache
      - *git-config
      - run: npm version major
      - *git-commit-tags

  release:
    <<: *docker-setup
    steps:
      - attach_workspace:
          at: ~/repo
      - *yarn-config
      - run: npm publish

workflows:
  version: 2
  test_and_build:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - test
            - lint
  # Version bump is disable until circle ci supports conditional steps.
  #  version_bump:
  #    jobs:
  #      - install:
  #          filters:
  #            branches:
  #              only: master
  #      - build:
  #          requires:
  #            - install
  #      - approval-patch:
  #          type: approval
  #          requires:
  #            - build
  #      - approval-minor:
  #          type: approval
  #          requires:
  #            - build
  #      - approval-major:
  #          type: approval
  #          requires:
  #            - build
  #      - patch:
  #          requires:
  #            - approval-patch
  #      - minor:
  #          requires:
  #            - approval-minor
  #      - major:
  #          requires:
  #            - approval-major
  release_version:
    jobs:
      - install:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - approval-release:
          type: approval
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - approval-release
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
